version: '3.8'

services:
  app:
    image: ghcr.io/jorguzz-fer/aquinaotem:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.routers-aquinaotem-app.rule=Host(`app.aquinaotem.com.br`)"
      - "traefik.http.routers.routers-aquinaotem-app.service=svc-aquinaotem-app"
      - "traefik.http.services.svc-aquinaotem-app.loadbalancer.server.port=3000"
      - "traefik.docker.network=WOWmais"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.routers-aquinaotem-app.rule=Host(`app.aquinaotem.com.br`)"
        - "traefik.http.routers.routers-aquinaotem-app.service=svc-aquinaotem-app"
        - "traefik.http.services.svc-aquinaotem-app.loadbalancer.server.port=3000"
        - "traefik.docker.network=WOWmais"
        # - "traefik.http.routers.aquinaotem-secure.entrypoints=websecure"
        # - "traefik.http.routers.aquinaotem-secure.tls.certresolver=letsencryptresolver"
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 256M
        # IMPORTANTE: O serviço precisa estar na mesma rede do Traefik
    networks:
      - WOWmais

    environment:
      - DATABASE_URL=${DATABASE_URL}

networks:
  # Nome da rede externa onde o Traefik está rodando.
  # Confirme se o nome é 'traefik-public', 'proxy', ou 'web'.
  WOWmais:
    external: true
