version: '3.8'

services:
  app:
    image: ghcr.io/jorguzz-fer/aquinaotem:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        # Habilitar Traefik para este serviço
        - "traefik.enable=true"
        # Configurar Router para HTTP (Porta 80)
        - "traefik.http.routers.aquinaotem.rule=Host(`app.aquinaotem.com.br`)"
        - "traefik.http.routers.aquinaotem.entrypoints=web"
        # Configurar Serviço
        - "traefik.http.routers.aquinaotem.service=aquinaotem-svc"
        - "traefik.http.services.aquinaotem-svc.loadbalancer.server.port=3000"
        - "traefik.docker.network=WOWmais"
        # Opcional: Configurar HTTPS (Porta 443 + Certificado)
        # Descomente as linhas abaixo se tiver Resolver de certificado configurado (ex: letsencrypt)
        # - "traefik.http.routers.aquinaotem-secure.rule=Host(`aquinaotem.wowmais.com.br`)"
        # - "traefik.http.routers.aquinaotem-secure.entrypoints=websecure"
        # - "traefik.http.routers.aquinaotem-secure.tls.certresolver=letsencryptresolver"

        # IMPORTANTE: O serviço precisa estar na mesma rede do Traefik
    networks:
      - WOWmais

    environment:
      - DATABASE_URL=${DATABASE_URL}

networks:
  # Nome da rede externa onde o Traefik está rodando.
  # Confirme se o nome é 'traefik-public', 'proxy', ou 'web'.
  WOWmais:
    external: true
