version: '3.8'

services:
  app:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-test.rule=Host(`app.aquinaotem.com.br`)"
      - "traefik.http.services.whoami-test.loadbalancer.server.port=80"
      - "traefik.docker.network=WOWmais"
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        # Router
        - "traefik.http.routers.whoami-test.rule=Host(`app.aquinaotem.com.br`)"
        # Explicit Service (Standard Swarm)
        - "traefik.http.services.whoami-test.loadbalancer.server.port=80"
        # Network
        - "traefik.docker.network=WOWmais"
    networks:
      - WOWmais

networks:
  WOWmais:
    external: true
