version: '3.8'

services:
  app:
    image: ghcr.io/jorguzz-fer/aquinaotem:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.routers-aquinaotem-app.rule=Host(`app.aquinaotem.com.br`)"
      - "traefik.http.routers.routers-aquinaotem-app.service=svc-aquinaotem-app"
      - "traefik.http.services.svc-aquinaotem-app.loadbalancer.server.port=3000"
      - "traefik.docker.network=WOWmais"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.routers-aquinaotem-app.rule=Host(`app.aquinaotem.com.br`)"
        - "traefik.http.routers.routers-aquinaotem-app.service=svc-aquinaotem-app"
        - "traefik.http.services.svc-aquinaotem-app.loadbalancer.server.port=3000"
        - "traefik.docker.network=WOWmais"
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 256M

    networks:
      - WOWmais

    environment:
      - DATABASE_URL=${DATABASE_URL}

networks:
  # O nome da rede deve ser o mesmo usado pelo Traefik no novo servidor
  WOWmais:
    external: true
