version: '3.8'

services:
  app:
    container_name: aquinaotem-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:6f3ca85da664c64140a80d004d894143@10.0.1.156:5432/aquinaotem
    # Uncomment lines below if you need to persist uploaded files or logs
    # volumes:
    #   - ./uploads:/app/public/uploads
