services:
  app:
    container_name: aquinaotem-app
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && npx prisma migrate deploy && npm start"
    volumes:
      - .:/app
